package dev.jcasaslopez.user.enums;

public enum LoginFailureReason {
	INCORRECT_PASSWORD,
    USER_NOT_FOUND,
    MISSING_FIELD,
    ACCOUNT_LOCKED,
    TOKEN_EXPIRED,
    TOKEN_MALFORMED,
    TOKEN_INVALID_SIGNATURE,
    TOKEN_MISSING,
    TOKEN_BLACKLISTED,
    OTHER_REASON
}
